compressionLevel: mixed

enableGlobalCache: false

packageExtensions:
  "@mantine/core@^5":
    peerDependencies:
      "@emotion/react": ^11
  "@mantine/next@^5":
    peerDependencies:
      "@emotion/react": ^11
      "@emotion/server": ^11

yarnPath: .yarn/releases/yarn-4.0.1.cjs
