packageExtensions:
  "@mantine/core@^5":
    peerDependencies:
      "@emotion/react": ^11
  "@mantine/next@^5":
    peerDependencies:
      "@emotion/react": ^11
      "@emotion/server": ^11

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.2.3.cjs
