packageExtensions:
  "@mantine/core@5.0.0":
    peerDependencies:
      "@emotion/react": "*"
  "@mantine/next@5.0.0":
    peerDependencies:
      "@emotion/react": "*"
      "@emotion/server": "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.2.1.cjs
