name: Tests

on:
  push:
    branches: [master]
  pull_request:
    types: [opened, reopened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: "16.x"

jobs:
  run-tests:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "yarn" # https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#caching-packages-dependencies
      - name: Install dependencies
        run: |
          yarn --immutable
          yarn playwright install --with-deps
      - name: Run linter
        run: yarn lint
      - name: Run build
        run: yarn build
      - name: Run tests
        run: yarn test
      - name: Run e2e tests
        run: yarn test:e2e
