name: Tests

on:
  push:
    branches: [master]
  pull_request:
    types: [opened, reopened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: "16.x"

jobs:
  run-tests:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            playwright-cache-path: "~/.cache/ms-playwright"
          - os: macos-latest
            playwright-cache-path: "~/Library/Caches/ms-playwright"
          - os: windows-latest
            playwright-cache-path: '%USERPROFILE%\AppData\Local\ms-playwright'

    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "yarn" # https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#caching-packages-data

      - name: Install dependencies
        run: yarn --immutable

      - name: Run linter
        run: yarn lint

      - name: Run build
        run: yarn build

      - name: Run tests
        run: yarn test

      - name: "[E2E] Get cache key"
        id: playwright-version
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const util = require('util');
            const packageJsonBuffer = await util.promisify(fs.readFile)('package.json');
            const packageJson = JSON.parse(packageJsonBuffer.toString());
            return packageJson.devDependencies['@playwright/test'];
          result-encoding: string

      - name: "[E2E] Cache dependencies"
        uses: actions/cache@v3
        id: playwright-cache
        with:
          path: ${{ matrix.playwright-cache-path }}
          key: "${{ runner.os }}-playwright-${{ steps.playwright-version.outputs.result }}"
          restore-keys: ${{ runner.os }}-playwright-

      - name: "[E2E] Install dependencies"
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: yarn playwright install --with-deps

      - name: "[E2E] Install dependencies (runtime only)"
        if: steps.playwright-cache.outputs.cache-hit == 'true'
        run: yarn playwright install-deps

      - name: "[E2E] Run tests"
        run: yarn test:e2e
